const sql = require('mssql');

const config = {
  user: 'sa',
  password: 'Shobha@123',
  server: '127.0.0.1',
  port: 1433,
  database: 'NBT_DB',
  options: { encrypt: false, trustServerCertificate: true }
};

async function run() {
  try {
    let pool = await sql.connect(config);
    console.log('Connected to NBT_DB. Creating users table if not exists...');
    
    await pool.request().query(`
      IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'users')
      BEGIN
          CREATE TABLE users (
              id INT IDENTITY(1,1) PRIMARY KEY,
              name VARCHAR(100),
              email VARCHAR(100) UNIQUE,
              password VARCHAR(255),
              role VARCHAR(50),
              phone_number VARCHAR(20),
              profile_picture VARCHAR(255),
              about_me TEXT,
              team VARCHAR(100),
              joining_date DATE,
              token_version INT DEFAULT 0,
              status VARCHAR(50) DEFAULT 'Active'
          );
          
          -- Insert a dummy admin user
          -- The password hash below is for 'admin123' generated by bcrypt(10)
          INSERT INTO users (name, email, password, role, status)
          VALUES ('Admin', 'admin@nbt.com', '$2b$10$wT8K48.pW4t38Zz53oI3/.E8Jt6a/9.J98hYy3qR/k3Uq.5O5pX4W', 'Admin', 'Active');
      END
    `);
    
    console.log('Successfully created users table and dummy admin.');
    process.exit(0);
  } catch (err) {
    console.error("DB Error:", err);
    process.exit(1);
  }
}
run();
